"use client";

import type { Metadata } from "next";
import { createContext, ReactNode } from "react";
import { Inter } from "next/font/google";
import "./globals.css";
import { FilterProvider } from "@/components/Test";

const inter = Inter({ subsets: ["latin"] });

interface AppContextType {
  brandList: { label: string; brand: string; id: string }[];
  colorList: { label: string; color: string; id: string }[];
}

export const AppContext = createContext<AppContextType>({
  brandList: [],
  colorList: [],
});

const colorList = [
  { label: "Red", color: "red", id: "color-1Aa2" },
  { label: "Blue", color: "blue", id: "color-BbC3" },
  { label: "Green", color: "green", id: "color-DdE4" },
  { label: "Yellow", color: "yellow", id: "color-FfG5" },
  { label: "Purple", color: "purple", id: "color-HhI6" },
  { label: "Orange", color: "orange", id: "color-JjK7" },
  { label: "Pink", color: "pink", id: "color-LlM8" },
  { label: "Brown", color: "brown", id: "color-NnO9" },
  { label: "Gray", color: "gray", id: "color-PpQ10" },
  { label: "Cyan", color: "cyan", id: "color-RrS11" },
];

const brandList = [
  { label: "Apple", brand: "Apple", id: "brand-1Aa2" },
  { label: "Nike", brand: "Nike", id: "brand-BbC3" },
  { label: "Google", brand: "Google", id: "brand-DdE4" },
  { label: "Coca-Cola", brand: "Coca-Cola", id: "brand-FfG5" },
  { label: "Microsoft", brand: "Microsoft", id: "brand-HhI6" },
  { label: "Amazon", brand: "Amazon", id: "brand-JjK7" },
  { label: "Samsung", brand: "Samsung", id: "brand-LlM8" },
  { label: "Toyota", brand: "Toyota", id: "brand-NnO9" },
  { label: "McDonald's", brand: "McDonald's", id: "brand-PpQ10" },
  { label: "Adidas", brand: "Adidas", id: "brand-RrS11" },
  { label: "Facebook", brand: "Facebook", id: "brand-TtU12" },
  { label: "Volkswagen", brand: "Volkswagen", id: "brand-VvW13" },
];

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppContext.Provider value={{ brandList, colorList }}>
          <FilterProvider>{children}</FilterProvider>
        </AppContext.Provider>
      </body>
    </html>
  );
}
